# Generated by Django 4.2.15 on 2024-08-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_ponguser_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ponguser',
            managers=[
            ],
        ),
    ]
