# Generated by Django 4.2.15 on 2024-08-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_ponguser_banner_picture_and_more'),
        ('login', '0002_ponguser_email'),
    ]

    operations = [
    ]
