# Generated by Django 4.2.15 on 2024-08-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_ponguser_banner_picture_and_more'),
        ('login', '0004_alter_ponguser_banner_picture_and_more'),
    ]

    operations = [
    ]
