# Generated by Django 4.2.15 on 2024-08-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_merge_20240815_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponguser',
            name='email',
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='banner_picture',
            field=models.ImageField(blank=True, default='/static/pong/img/banner.jpeg', null=True, upload_to='static/userImages/'),
        ),
    ]
