# Generated by Django 4.2.15 on 2024-08-18 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_ponguser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponguser',
            name='email',
        ),
    ]
