# Generated by Django 4.2.15 on 2024-08-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_ponguser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='down_key',
            field=models.CharField(blank=True, default='s', max_length=1, null=True),
        ),
        migrations.RemoveField(
            model_name='ponguser',
            name='friends',
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='up_key',
            field=models.CharField(blank=True, default='w', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='ponguser',
            name='friends',
            field=models.JSONField(default=list),
        ),
    ]
