# Generated by Django 4.2.15 on 2024-08-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_ponguser_down_key_remove_ponguser_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
