# Generated by Django 4.2.15 on 2024-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_ponguser_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='banner_picture',
            field=models.ImageField(blank=True, default='static/pong/img/banner.jpeg', null=True, upload_to='static/userImages/'),
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/pong/img/p1.png', null=True, upload_to='static/userImages/'),
        ),
    ]
