# Generated by Django 4.2.15 on 2024-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_ponguser_banner_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponguser',
            name='down_key',
            field=models.CharField(blank=True, default='s', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ponguser',
            name='up_key',
            field=models.CharField(blank=True, default='w', max_length=255, null=True),
        ),
    ]
