# Generated by Django 4.2.15 on 2024-08-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_ponguser_banner_picture_and_more'),
    ]

    operations = [
    ]
