# Generated by Django 4.2.15 on 2024-08-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_merge_20240824_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponguser',
            name='status',
            field=models.CharField(default='offline', max_length=255),
        ),
    ]
