# Generated by Django 4.2.15 on 2024-08-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_ponguser_down_key_alter_ponguser_up_key'),
        ('login', '0014_ponguser_status'),
    ]

    operations = [
    ]
