# Generated by Django 4.2.15 on 2024-08-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_merge_20240828_1425'),
        ('login', '0015_merge_20240828_2010'),
    ]

    operations = [
    ]
