version: '3.9'

services:
  django_daphne:
    build: ./django

    ports:
      - "8000:8000"

    volumes:
      - ./django/backend/static:/app/static
      - ./django/backend:/app

    command: daphne -u /tmp/daphne.sock myproject.asgi:application
    
    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.15

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx

    ports:
      - "80:80"    # Alterar porta HTTPS
      - "443:443"   # Alterar porta HTTPS
      # - "443:443"

    volumes:
      - ./django/backend/static:/static
      - ./ssl:/etc/nginx/ssl


    depends_on:
      - django_daphne


volumes:
  static:
  postgres_data:

