version: '3.9'

services:
  django_daphne:
    build: 
      context: ./django

    ports:
      - "8000:8000"

    volumes:
      # - static:/static
      - ./django/backend:/app

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13.15

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx

    ports:
      - "8080:81"

    volumes:
      # - static:/static
      - ./django/backend/static:/static

    depends_on:
      - django_gunicorn

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  static:
  postgres_data:


