services:
  django_daphne:
    build: ./django

    ports:
      - "8000:8000"

    volumes:
      - ./django/backend/static:/app/static
      - ./django/backend:/app

    command: daphne -u /tmp/daphne.sock myproject.asgi:application

    env_file:
      - .env

    depends_on:
      - postgres
      - redis
    networks:
      - backend

  postgres:
    image: postgres:13

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx

    ports:
      - "8080:80"    # Alterar porta HTTPS
      - "8443:443"   # Alterar porta HTTPS
      # - "443:443"

    volumes:
      - ./django/backend/static:/static
      - ./ssl:/etc/nginx/ssl


    depends_on:
      - django_daphne

    networks:
      - backend


volumes:
  static:
  postgres_data:

networks:
  backend:
