# Generated by Django 4.2.15 on 2024-08-15 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.JSONField(default=list)),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
                ('scoreList', models.JSONField(default=list)),
                ('playerHost', models.CharField(max_length=255)),
            ],
        ),
    ]
