# Generated by Django 4.2.15 on 2024-08-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='type',
            new_name='game_type',
        ),
        migrations.AddField(
            model_name='game',
            name='numberPlayers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
