# Generated by Django 4.2.15 on 2024-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_game_game_type_game_numberplayers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
