# Generated by Django 4.2.15 on 2024-08-24 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.JSONField(default=list)),
                ('status', models.CharField(max_length=255)),
                ('block', models.BooleanField(default=False)),
                ('mensagens', models.JSONField(default=list)),
                ('createDate', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
