# Generated by Django 4.2.15 on 2024-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='block',
            field=models.JSONField(default=list),
        ),
    ]
