# Generated by Django 4.2.15 on 2024-08-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Default Chat Name', max_length=400),
        ),
        migrations.AlterField(
            model_name='chat',
            name='block',
            field=models.JSONField(default=list),
        ),
    ]
