# Generated by Django 4.2.15 on 2024-08-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='block',
        ),
    ]
