# Generated by Django 4.2.15 on 2024-08-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='block_temp',
            field=models.JSONField(default=list),
        ),
    ]
