# Generated by Django 4.2.15 on 2024-08-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_block_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='block_temp',
        ),
    ]
