# Generated by Django 4.2.15 on 2024-08-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_block_field'),
    ]

    operations = [
    ]
