# Generated by Django 4.2.15 on 2024-08-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_block_field'),
        ('chat', '0007_remove_block_field'),
    ]

    operations = [
    ]
