# Generated by Django 4.2.15 on 2024-08-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_merge_0006_remove_block_field_0007_remove_block_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='block',
            field=models.JSONField(default=list),
        ),
    ]
