# Generated by Django 4.2.15 on 2024-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_add_block_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default='Chat Padrao', max_length=400),
            preserve_default=False,
        ),
    ]
